version: '3.8'

services:
  app:
    container_name: organizer-api
    image: nesrux/organizer-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:

