version: '3.8'

services:
  app:
    container_name: organizer-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend

networks:
  backend:
